/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppWorkshopsIndexRouteImport } from './routes/_app/workshops/index'
import { Route as AppWorkshopsWorkshopIdRouteImport } from './routes/_app/workshops/$workshopId'
import { Route as AppWorkshopsNewRouteImport } from './routes/_app/workshops/new'
import { Route as AppWorkshopsWorkshopIdEditRouteImport } from './routes/_app/workshops/$workshopId_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkshopsIndexRoute = AppWorkshopsIndexRouteImport.update({
  id: '/workshops/',
  path: '/workshops/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkshopsWorkshopIdRoute = AppWorkshopsWorkshopIdRouteImport.update({
  id: '/workshops/$workshopId',
  path: '/workshops/$workshopId',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkshopsNewRoute = AppWorkshopsNewRouteImport.update({
  id: '/workshops/new',
  path: '/workshops/new',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkshopsWorkshopIdEditRoute =
  AppWorkshopsWorkshopIdEditRouteImport.update({
    id: '/workshops/$workshopId_/edit',
    path: '/workshops/$workshopId/edit',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/users': typeof AppUsersRoute
  '/workshops/$workshopId': typeof AppWorkshopsWorkshopIdRoute
  '/workshops/new': typeof AppWorkshopsNewRoute
  '/workshops/': typeof AppWorkshopsIndexRoute
  '/workshops/$workshopId/edit': typeof AppWorkshopsWorkshopIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/users': typeof AppUsersRoute
  '/workshops/$workshopId': typeof AppWorkshopsWorkshopIdRoute
  '/workshops/new': typeof AppWorkshopsNewRoute
  '/workshops': typeof AppWorkshopsIndexRoute
  '/workshops/$workshopId/edit': typeof AppWorkshopsWorkshopIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/workshops/$workshopId': typeof AppWorkshopsWorkshopIdRoute
  '/_app/workshops/new': typeof AppWorkshopsNewRoute
  '/_app/workshops/': typeof AppWorkshopsIndexRoute
  '/_app/workshops/$workshopId_/edit': typeof AppWorkshopsWorkshopIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/users'
    | '/workshops/$workshopId'
    | '/workshops/new'
    | '/workshops/'
    | '/workshops/$workshopId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/users'
    | '/workshops/$workshopId'
    | '/workshops/new'
    | '/workshops'
    | '/workshops/$workshopId/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/users'
    | '/_app/workshops/$workshopId'
    | '/_app/workshops/new'
    | '/_app/workshops/'
    | '/_app/workshops/$workshopId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workshops/': {
      id: '/_app/workshops/'
      path: '/workshops'
      fullPath: '/workshops/'
      preLoaderRoute: typeof AppWorkshopsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workshops/$workshopId': {
      id: '/_app/workshops/$workshopId'
      path: '/workshops/$workshopId'
      fullPath: '/workshops/$workshopId'
      preLoaderRoute: typeof AppWorkshopsWorkshopIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workshops/new': {
      id: '/_app/workshops/new'
      path: '/workshops/new'
      fullPath: '/workshops/new'
      preLoaderRoute: typeof AppWorkshopsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workshops/$workshopId_/edit': {
      id: '/_app/workshops/$workshopId_/edit'
      path: '/workshops/$workshopId/edit'
      fullPath: '/workshops/$workshopId/edit'
      preLoaderRoute: typeof AppWorkshopsWorkshopIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppUsersRoute: typeof AppUsersRoute
  AppWorkshopsWorkshopIdRoute: typeof AppWorkshopsWorkshopIdRoute
  AppWorkshopsNewRoute: typeof AppWorkshopsNewRoute
  AppWorkshopsIndexRoute: typeof AppWorkshopsIndexRoute
  AppWorkshopsWorkshopIdEditRoute: typeof AppWorkshopsWorkshopIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppUsersRoute: AppUsersRoute,
  AppWorkshopsWorkshopIdRoute: AppWorkshopsWorkshopIdRoute,
  AppWorkshopsNewRoute: AppWorkshopsNewRoute,
  AppWorkshopsIndexRoute: AppWorkshopsIndexRoute,
  AppWorkshopsWorkshopIdEditRoute: AppWorkshopsWorkshopIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
