/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppWorkshopsIndexRouteImport } from './routes/_app/workshops/index'
import { Route as AppWorkshopsWorkshopIdRouteImport } from './routes/_app/workshops/$workshopId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkshopsIndexRoute = AppWorkshopsIndexRouteImport.update({
  id: '/workshops/',
  path: '/workshops/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkshopsWorkshopIdRoute = AppWorkshopsWorkshopIdRouteImport.update({
  id: '/workshops/$workshopId',
  path: '/workshops/$workshopId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/users': typeof AppUsersRoute
  '/workshops/$workshopId': typeof AppWorkshopsWorkshopIdRoute
  '/workshops/': typeof AppWorkshopsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/users': typeof AppUsersRoute
  '/workshops/$workshopId': typeof AppWorkshopsWorkshopIdRoute
  '/workshops': typeof AppWorkshopsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/workshops/$workshopId': typeof AppWorkshopsWorkshopIdRoute
  '/_app/workshops/': typeof AppWorkshopsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/users' | '/workshops/$workshopId' | '/workshops/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/users' | '/workshops/$workshopId' | '/workshops'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/users'
    | '/_app/workshops/$workshopId'
    | '/_app/workshops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workshops/': {
      id: '/_app/workshops/'
      path: '/workshops'
      fullPath: '/workshops/'
      preLoaderRoute: typeof AppWorkshopsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workshops/$workshopId': {
      id: '/_app/workshops/$workshopId'
      path: '/workshops/$workshopId'
      fullPath: '/workshops/$workshopId'
      preLoaderRoute: typeof AppWorkshopsWorkshopIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppUsersRoute: typeof AppUsersRoute
  AppWorkshopsWorkshopIdRoute: typeof AppWorkshopsWorkshopIdRoute
  AppWorkshopsIndexRoute: typeof AppWorkshopsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppUsersRoute: AppUsersRoute,
  AppWorkshopsWorkshopIdRoute: AppWorkshopsWorkshopIdRoute,
  AppWorkshopsIndexRoute: AppWorkshopsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
